/**
 Author: Renaun Erickson @renaun http://renaun.com
 Live three.js Texture Update Plugin

 Meant for development of designing textures in connection with
 Photoshop CC Generator feature.

 You will have to point your assets urls to the folder generated by
 Photoshop CC Generator.

 Usage:
      include renaun.three.ltup.js after three library

      // After you instantiate your threejs renderer add this code
      renderer.addPostPlugin(new RENAUN.LiveTextureUpdatePlugin());
**/
var RENAUN = {
    cacheLiveTextureUpdates: {},
    updateFrameRate: 30
};
    
THREE.ImageUtils.loadTexture = function ( url, mapping, onLoad, onError ) {

    var loader = new THREE.ImageLoader();
    loader.crossOrigin = this.crossOrigin;

    var texture;
    if (!RENAUN.cacheLiveTextureUpdates[url])
    {
        texture = new THREE.Texture( undefined, mapping );
        RENAUN.cacheLiveTextureUpdates[url] = {size: 0, texture: texture, url: url };
    }
    else
    {
        texture = RENAUN.cacheLiveTextureUpdates[url].texture;
    }
    
    var image = loader.load( url, function () {

        texture.needsUpdate = true;

        if ( onLoad ) onLoad( texture );

    } );
    texture.image = image;
    texture.sourceFile = url;

    return texture;
}

RENAUN.LiveTextureUpdatePlugin = function () {
    
    var count = 0;
    
    this.init = function ( renderer ) { }
    
    this.render = function ( scene, camera, viewportWidth, viewportHeight ) {
        count++;
        if (count % RENAUN.updateFrameRate !== 0)
            return;
        for (var key in RENAUN.cacheLiveTextureUpdates)
        {
            THREE.ImageUtils.loadTexture(key);  
        }
        if (count > 300000000)
            count = 0;
    }
}